import java.awt.Dimension;
import java.awt.Graphics;
import java.io.Serializable;



/**
 *
 * @author Enrique
 */
public class GraficoDeBarras extends javax.swing.JPanel implements Serializable{

    /**
     * Creates new form GraficoDeBarras
     */
  public Barrita barra = new Barrita();
    public GraficoDeBarras() {
        initComponents();
    }
    

  @Override
  protected void paintComponent(Graphics g2){
        super.paintComponent(g2);
          barra.tamV = new Dimension(getWidth(), getHeight());
              add(barra.crearGrafico());
              barra.insertarValoresX();
}
 

      public ValuesBar getPValores(){
          return barra.val;
      }
      
      public void setPValores(ValuesBar x){
          ValuesBar old = this.barra.val;
          this.barra.val = x;
          
          firePropertyChange("PValores", old, x);
      }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
